# docker-compose.yml
#https://finestructure.co/blog/2016/5/16/monitoring-with-prometheus-grafana-docker-part-1
version: '2'
services:
    prometheus:
        image: prom/prometheus:0.18.0
        volumes:
            - prometheus_data:/prometheus
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
    node-exporter:
        image: prom/node-exporter:latest
        ports:
            - '9100:9100'
    grafana:
        image: grafana/grafana:latest
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=password
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
        volumes:
            - ./data/grafana:/var/lib/grafana
        
volumes:
    prometheus_data: {}
    grafana_data: {}